language: php

sudo: false

dist: trusty

cache:
    directories:
        - $HOME/.composer/cache

install: composer update $COMPOSER_FLAGS

matrix:
    include:
        -
            php: 8.0
        -
            php: 8.0
            env: COMPOSER_FLAGS='--prefer-lowest'
        -
            php: nightly
            env: COMPOSER_FLAGS='--ignore-platform-reqs'
    allow_failures:
        - php: nightly

script:
    - vendor/bin/phpunit
    - vendor/bin/phpspec run
