<?php

declare(strict_types=1);

namespace Zlikavac32\Rick\Examples;

use Zlikavac32\Enum\Enum;

require_once __DIR__ . '/../vendor/autoload.php';

/**
 * This is simple example shown also in the README.md file. Simplest definition and usage are highlighted here.
 */

/**
 * @method static YesNo YES
 * @method static YesNo NO
 */
abstract class YesNo extends Enum
{

}

//We can type-hint our enum
function yesNo(YesNo $yesNo)
{
    //Switch-case also works
    switch ($yesNo) {
        case YesNo::NO():
            var_dump('No');
            break;
        case YesNo::YES():
            var_dump('Yes');
            break;
    }
}

//Both identity and value checks work
var_dump(YesNo::YES() === YesNo::NO()); // bool(false)
var_dump(YesNo::YES() == YesNo::NO()); // bool(false)

var_dump(YesNo::YES() === YesNo::YES()); // bool(true)
var_dump(YesNo::YES() == YesNo::YES()); // bool(true)

yesNo(YesNo::NO()); // string(2) "No"
yesNo(YesNo::YES()); // string(3) "Yes"

//Ordinal is generated directly from the array that's generated by enum class
var_dump(
    YesNo::NO()
        ->ordinal(),
    YesNo::YES()
        ->ordinal()
);

// int(1)
// int(0)

