name: PHP Enum

on: [push, pull_request]

jobs:
    build:

        runs-on: ubuntu-latest
        strategy:
            matrix:
                composer_flags: [ '', '--prefer-lowest' ]

        steps:
            - uses: actions/checkout@v2

            - name: Validate composer.json and composer.lock
              run: composer validate

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v2
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ matrix.composer_flags }}-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-${{ matrix.composer_flags }}-

            - name: Install dependencies
              if: steps.composer-cache.outputs.cache-hit != 'true'
              run: composer upgrade ${{ matrix.composer_flags }} --no-progress --no-suggest

            - name: Run phpspec
              run: vendor/bin/phpspec run

            - name: Run PHPUnit
              run: vendor/bin/phpunit
